language: python
python:
  - "3.5"  # You are using Python 3.5, but consider upgrading

# command to install dependencies
install:
  - pip install -r requirements.txt  # Ensure you have other necessary dependencies, or leave it out if empty

# command to run tests
script:
  - python -m unittest discover -s tests -p "TestTriangle.py"  # Adjust paths based on your project structure
