language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt  # Install the dependencies (without unittest)
script:
  - python -m unittest discover  # This command will discover and run all the tests
